# Use our custom Dockerfile for environment
image:
  file: .gitpod.Dockerfile

# Automatically install project dependencies and start Jupyter Notebook
tasks:
  - init: pip install -r requirements.txt
  - command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser

# Expose Jupyter Notebook port
ports:
  - port: 8888
    onOpen: open-preview

# Recommend VS Code extensions
vscode:
  extensions:
    - ms-python.python